heat_template_version: rocky

parameters:
  servers:
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  StandaloneStandardExtraConfigPost:
    type: ../../extraconfig/post_deploy/standalone_post.yaml
    properties:
       servers:  {get_param: servers}
       EndpointMap:  {get_param: EndpointMap}

  IronicVBMCSetup:
    type: vbmc_setup.yaml
    properties:
       servers:  {get_param: servers}

