#OpenStack version number
version: 13
#Nuage Release and format is <Major-release, use '-' instead of '.'>-<Minor-release>-<Updated-release>
release: 5-4-1-u3
#Tag for Nuage container images
tag: latest
#Undercloud Local Registry IP Address : PORT
local_registry: 192.168.24.1:8787
#List of Nuage containers ( For AVRS, please include 'nova-compute' as well)
nuage_images: ['heat-api-cfn', 'heat-api', 'heat-engine', 'horizon', 'neutron-server']
