# A Heat environment file which can be used to enable a
# a Neutron Nuage backend on the controller, configured via puppet
parameter_defaults:
  ControllerExtraConfig:
    neutron::config::server_config:
      DEFAULT/ipam_driver:
        value: nuage_internal
      DEFAULT/enable_snat_by_default:
        value: false
  EnableVLANTransparency: true
  NeutronNuageNetPartitionName: 'DefaultOrg'
  NeutronNuageVSDIp: '192.168.24.122:8443'
  NeutronNuageVSDUsername: 'csproot'
  NeutronNuageVSDPassword: 'csproot'
  NeutronNuageVSDOrganization: 'csp'
  NeutronNuageBaseURIVersion: 'v6'
  NeutronNuageCMSId: '3d46e040-8cd6-4c12-b187-703e7cdb02de'
  UseForwardedFor: true
  NeutronPluginMl2PuppetTags: 'neutron_plugin_ml2,neutron_plugin_nuage'
  NeutronServicePlugins: 'NuagePortAttributes,NuageAPI,NuageL3,trunk'
  NeutronDBSyncExtraParams: '--config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini --config-file /etc/neutron/plugins/nuage/plugin.ini'
  NeutronTypeDrivers: 'vlan,vxlan,flat'
  NeutronNetworkType: 'vxlan'
  NeutronMechanismDrivers: 'nuage,nuage_baremetal'
  NeutronPluginExtensions: 'nuage_subnet,nuage_port,port_security,nuage_network'
  NeutronFlatNetworks: '*'
  NeutronTunnelIdRanges: ''
  NeutronNetworkVLANRanges: ''
  NeutronVniRanges: '1001:2000'
  NovaOVSBridge: 'alubr0'
  NeutronMetadataProxySharedSecret: 'NuageNetworksSharedSecret'
  InstanceNameTemplate: 'inst-%08x'
  HeatEnginePluginDirs: ['/usr/lib/python2.7/site-packages/nuage-heat/']
  HorizonCustomizationModule: 'nuage_horizon.customization'
  HorizonVhostExtraParams:
    add_listen: true
    priority: 10
    access_log_format: '%a %l %u %t \"%r\" %>s %b \"%%{}{Referer}i\" \"%%{}{User-Agent}i\"'
    aliases: [{'alias': '%{root_url}/static/nuage', 'path': '/usr/lib/python2.7/site-packages/nuage_horizon/static'}, {'alias': '%{root_url}/static', 'path': '/usr/share/openstack-dashboard/static'}]